---
- name: "Create the Base Domain"
  community.general.ldap_entry:
    dn: "{{ dn_suffix }}"
    objectClass: "domain"
    attributes:
      dc: "{{ dn_suffix.split(',')[0].split('=')[1] }}"
    bind_dn: "cn=Manager,{{ dn_suffix }}"
    bind_pw: "{{ root_password }}"
    state: "present"

- name: "Organizational Unit: People"
  community.general.ldap_entry:
    dn: "ou=People,{{ dn_suffix }}"
    objectClass: "organizationalUnit"
    attributes:
      ou: "People"
    bind_dn: "cn=Manager,{{ dn_suffix }}"
    bind_pw: "{{ root_password }}"
    state: "present"

- name: "Organizational Unit: Groups"
  community.general.ldap_entry:
    dn: "ou=Groups,{{ dn_suffix }}"
    objectClass: "organizationalUnit"
    attributes:
      ou: "Groups"
    bind_dn: "cn=Manager,{{ dn_suffix }}"
    bind_pw: "{{ root_password }}"
    state: "present"

- name: "Group: everyone"
  community.general.ldap_entry:
    dn: "cn=everyone,ou=Groups,{{ dn_suffix }}"
    objectClass: "posixGroup"
    attributes:
      description: "All users"
      gidNumber: "10000"
    bind_dn: "cn=Manager,{{ dn_suffix }}"
    bind_pw: "{{ root_password }}"
    state: "present"

- name: "Group: de_admins"
  community.general.ldap_entry:
    dn: "cn=de_admins,ou=Groups,{{ dn_suffix }}"
    objectClass: "posixGroup"
    attributes:
      description: "DE administrators"
      gidNumber: "10001"
    bind_dn: "cn=Manager,{{ dn_suffix }}"
    bind_pw: "{{ root_password }}"
    state: "present"

- name: "Group: community"
  community.general.ldap_entry:
    dn: "cn=community,ou=Groups,{{ dn_suffix }}"
    objectClass: "posixGroup"
    attributes:
      description: "All community users"
      gidNumber: "10002"
    bind_dn: "cn=Manager,{{ dn_suffix }}"
    bind_pw: "{{ root_password }}"
    state: "present"

- name: "Group: damap_admins"
  community.general.ldap_entry:
    dn: "cn=damap_admins,ou=Groups,{{ dn_suffix }}"
    objectClass: "posixGroup"
    attributes:
      description: "All damap_admins users"
      gidNumber: "100100"
    bind_dn: "cn=Manager,{{ dn_suffix }}"
    bind_pw: "{{ root_password }}"
    state: "present"

- name: "Group: invenio_admins"
  community.general.ldap_entry:
    dn: "cn=invenio_admins,ou=Groups,{{ dn_suffix }}"
    objectClass: "posixGroup"
    attributes:
      description: "All invenio_admins users"
      gidNumber: "100200"
    bind_dn: "cn=Manager,{{ dn_suffix }}"
    bind_pw: "{{ root_password }}"
    state: "present"

- name: "Group: cluster_admin"
  community.general.ldap_entry:
    dn: "cn=cluster_admin,ou=Groups,{{ dn_suffix }}"
    objectClass: "posixGroup"
    attributes:
      description: "All cluster_admin users"
      gidNumber: "100300"
    bind_dn: "cn=Manager,{{ dn_suffix }}"
    bind_pw: "{{ root_password }}"
    state: "present"
  
- name: "User: de_grouper"
  community.general.ldap_entry:
    dn: "uid=de_grouper,ou=People,{{ dn_suffix }}"
    objectClass: "inetOrgPerson,posixAccount,shadowAccount"
    attributes:
      uid: "de_grouper"
      mail: "de_grouper@example.org"
      sn: "Grouper"
      givenName: "DE"
      cn: "DE Grouper"
      title: "Other"
      o: "N/A"
      departmentNumber: "N/A"
      uidNumber: "40000"
      gidNumber: "10000"
      homeDirectory: "/home/de_grouper"
    bind_dn: "cn=Manager,{{ dn_suffix }}"
    bind_pw: "{{ root_password }}"
    state: "present"

- name: "Set the de_grouper password"
  community.general.ldap_passwd:
    dn: "uid=de_grouper,ou=People,{{ dn_suffix }}"
    passwd: "{{ de_grouper_password }}"
    bind_dn: "cn=Manager,{{ dn_suffix }}"
    bind_pw: "{{ root_password }}"

- name: "Add de_grouper to the 'everyone' Group"
  community.general.ldap_attrs:
    dn: "cn=everyone,ou=Groups,{{ dn_suffix }}"
    attributes:
      memberUid: "de_grouper"
    bind_dn: "cn=Manager,{{ dn_suffix }}"
    bind_pw: "{{ root_password }}"
    state: "present"

- name: "User: ldap_reader"
  community.general.ldap_entry:
    dn: "uid=ldap_reader,ou=People,{{ dn_suffix }}"
    objectClass: "inetOrgPerson,posixAccount,shadowAccount"
    attributes:
      uid: "ldap_reader"
      mail: "ldap_reader@example.org"
      sn: "Reader"
      givenName: "LDAP"
      cn: "LDAP Reader"
      title: "Other"
      o: "N/A"
      departmentNumber: "N/A"
      uidNumber: "40001"
      gidNumber: "10002"
      homeDirectory: "/home/ldap_reader"
    bind_dn: "cn=Manager,{{ dn_suffix }}"
    bind_pw: "{{ root_password }}"
    state: "present"

- name: "Set the ldap_reader password"
  community.general.ldap_passwd:
    dn: "uid=ldap_reader,ou=People,{{ dn_suffix }}"
    passwd: "{{ ldap_reader_password }}"
    bind_dn: "cn=Manager,{{ dn_suffix }}"
    bind_pw: "{{ root_password }}"

- name: "Add ldap_reader to the 'everyone' Group"
  community.general.ldap_attrs:
    dn: "cn=everyone,ou=Groups,{{ dn_suffix }}"
    attributes:
      memberUid: "ldap_reader"
    bind_dn: "cn=Manager,{{ dn_suffix }}"
    bind_pw: "{{ root_password }}"
    state: "present"

- name: "User: ldap_writer"
  community.general.ldap_entry:
    dn: "uid=ldap_writer,ou=People,{{ dn_suffix }}"
    objectClass: "inetOrgPerson,posixAccount,shadowAccount"
    attributes:
      uid: "ldap_writer"
      mail: "ldap_writer@example.org"
      sn: "Writer"
      givenName: "LDAP"
      cn: "LDAP Writer"
      title: "Other"
      o: "N/A"
      departmentNumber: "N/A"
      uidNumber: "40005"
      gidNumber: "10002"
      homeDirectory: "/home/ldap_writer"
    bind_dn: "cn=Manager,{{ dn_suffix }}"
    bind_pw: "{{ root_password }}"
    state: "present"

- name: "Set the ldap_writer password"
  community.general.ldap_passwd:
    dn: "uid=ldap_writer,ou=People,{{ dn_suffix }}"
    passwd: "{{ ldap_writer_password }}"
    bind_dn: "cn=Manager,{{ dn_suffix }}"
    bind_pw: "{{ root_password }}"

- name: "Add ldap_writer to the 'everyone' Group"
  community.general.ldap_attrs:
    dn: "cn=everyone,ou=Groups,{{ dn_suffix }}"
    attributes:
      memberUid: "ldap_writer"
    bind_dn: "cn=Manager,{{ dn_suffix }}"
    bind_pw: "{{ root_password }}"
    state: "present"

- name: "User: ldap_portal"
  community.general.ldap_entry:
    dn: "uid=ldap_portal,ou=People,{{ dn_suffix }}"
    objectClass: "inetOrgPerson,posixAccount,shadowAccount"
    attributes:
      uid: "ldap_portal"
      mail: "ldap_portal@example.org"
      sn: "Reader"
      givenName: "LDAP"
      cn: "LDAP Reader"
      title: "Other"
      o: "N/A"
      departmentNumber: "N/A"
      uidNumber: "40002"
      gidNumber: "10004"
      homeDirectory: "/home/ldap_portal"
    bind_dn: "cn=Manager,{{ dn_suffix }}"
    bind_pw: "{{ root_password }}"
    state: "present"

- name: "Set the ldap_portal password"
  community.general.ldap_passwd:
    dn: "uid=ldap_portal,ou=People,{{ dn_suffix }}"
    passwd: "{{ ldap_portal_password }}"
    bind_dn: "cn=Manager,{{ dn_suffix }}"
    bind_pw: "{{ root_password }}"

- name: "Add ldap_portal to the 'de_admins' Group"
  community.general.ldap_attrs:
    dn: "cn=de_admins,ou=Groups,{{ dn_suffix }}"
    attributes:
      memberUid: "ldap_portal"
    bind_dn: "cn=Manager,{{ dn_suffix }}"
    bind_pw: "{{ root_password }}"
    state: "present"

- name: "User: anonymous"
  community.general.ldap_entry:
    dn: "uid=anonymous,ou=People,{{ dn_suffix }}"
    objectClass: "inetOrgPerson,posixAccount,shadowAccount"
    attributes:
      uid: "anonymous"
      mail: "anonymous@example.org" # todo: get domain name
      sn: "Access"
      givenName: "Anonymous-Public"
      cn: "Anonymous-Public Access"
      title: "Other"
      o: "N/A" #TODO: ORG e.g. Graz University of technology
      departmentNumber: "N/A"
      uidNumber: "40004"
      gidNumber: "10008"
      homeDirectory: "/home/anonymous"
    bind_dn: "cn=Manager,{{ dn_suffix }}"
    bind_pw: "{{ root_password }}"
    state: "present"

- name: "Set the anonymous password"
  community.general.ldap_passwd:
    dn: "uid=anonymous,ou=People,{{ dn_suffix }}"
    passwd: "notprod"
    bind_dn: "cn=Manager,{{ dn_suffix }}"
    bind_pw: "{{ root_password }}"

- name: "Add anonymous to the 'everyone' Group"
  community.general.ldap_attrs:
    dn: "cn=everyone,ou=Groups,{{ dn_suffix }}"
    attributes:
      memberUid: "anonymous"
    bind_dn: "cn=Manager,{{ dn_suffix }}"
    bind_pw: "{{ root_password }}"
    state: "present"


##################
# Testing
# Todo: Remove
#################
- name: "User: damapuser"
  community.general.ldap_entry:
    dn: "uid=damapuser,ou=People,{{ dn_suffix }}"
    objectClass: "inetOrgPerson,posixAccount,shadowAccount"
    attributes:
      uid: "damapuser"
      mail: "damapuser@example.org" # todo: get domain name
      sn: "Access"
      givenName: "damapuser-damapgroup"
      cn: "damapuser-damapgroup Access"
      title: "Other"
      o: "N/A" #TODO: ORG e.g. Graz University of technology
      departmentNumber: "N/A"
      uidNumber: "40014"
      gidNumber: "10018"
      homeDirectory: "/home/damapuser"
    bind_dn: "cn=Manager,{{ dn_suffix }}"
    bind_pw: "{{ root_password }}"
    state: "present"

- name: "Set the damapuser password"
  community.general.ldap_passwd:
    dn: "uid=damapuser,ou=People,{{ dn_suffix }}"
    passwd: "notprod"
    bind_dn: "cn=Manager,{{ dn_suffix }}"
    bind_pw: "{{ root_password }}"

- name: "Add damapuser to the 'damap_admins' Group"
  community.general.ldap_attrs:
    dn: "cn=damap_admins,ou=Groups,{{ dn_suffix }}"
    attributes:
      memberUid: "damapuser"
    bind_dn: "cn=Manager,{{ dn_suffix }}"
    bind_pw: "{{ root_password }}"
    state: "present"

- name: "User: inveniouser"
  community.general.ldap_entry:
    dn: "uid=inveniouser,ou=People,{{ dn_suffix }}"
    objectClass: "inetOrgPerson,posixAccount,shadowAccount"
    attributes:
      uid: "inveniouser"
      mail: "inveniouser@example.org" # todo: get domain name
      sn: "Access"
      givenName: "inveniouser-damapgroup"
      cn: "inveniouser-damapgroup Access"
      title: "Other"
      o: "N/A" #TODO: ORG e.g. Graz University of technology
      departmentNumber: "N/A"
      uidNumber: "40024"
      gidNumber: "10028"
      homeDirectory: "/home/inveniouser"
    bind_dn: "cn=Manager,{{ dn_suffix }}"
    bind_pw: "{{ root_password }}"
    state: "present"

- name: "Set the inveniouser password"
  community.general.ldap_passwd:
    dn: "uid=inveniouser,ou=People,{{ dn_suffix }}"
    passwd: "notprod"
    bind_dn: "cn=Manager,{{ dn_suffix }}"
    bind_pw: "{{ root_password }}"

- name: "Add inveniouser to the 'invenio_admins' Group"
  community.general.ldap_attrs:
    dn: "cn=invenio_admins,ou=Groups,{{ dn_suffix }}"
    attributes:
      memberUid: "inveniouser"
    bind_dn: "cn=Manager,{{ dn_suffix }}"
    bind_pw: "{{ root_password }}"
    state: "present"

- name: "User: combineduser"
  community.general.ldap_entry:
    dn: "uid=combineduser,ou=People,{{ dn_suffix }}"
    objectClass: "inetOrgPerson,posixAccount,shadowAccount"
    attributes:
      uid: "combineduser"
      mail: "combineduser@example.org" # todo: get domain name
      sn: "Access"
      givenName: "combineduser-damap-invenio-group"
      cn: "combineduser-damap-invenio-group Access"
      title: "Other"
      o: "N/A" #TODO: ORG e.g. Graz University of technology
      departmentNumber: "N/A"
      uidNumber: "40034"
      gidNumber: "10038"
      homeDirectory: "/home/combineduser"
    bind_dn: "cn=Manager,{{ dn_suffix }}"
    bind_pw: "{{ root_password }}"
    state: "present"

- name: "Set the combineduser password"
  community.general.ldap_passwd:
    dn: "uid=combineduser,ou=People,{{ dn_suffix }}"
    passwd: "notprod"
    bind_dn: "cn=Manager,{{ dn_suffix }}"
    bind_pw: "{{ root_password }}"

- name: "Add combineduser to the 'invenio_admins' Group"
  community.general.ldap_attrs:
    dn: "cn=damap_admins,ou=Groups,{{ dn_suffix }}"
    attributes:
      memberUid: "combineduser"
    bind_dn: "cn=Manager,{{ dn_suffix }}"
    bind_pw: "{{ root_password }}"
    state: "present"

- name: "Add combineduser to the 'damap_admins' Group"
  community.general.ldap_attrs:
    dn: "cn=invenio_admins,ou=Groups,{{ dn_suffix }}"
    attributes:
      memberUid: "combineduser"
    bind_dn: "cn=Manager,{{ dn_suffix }}"
    bind_pw: "{{ root_password }}"
    state: "present"

- name: "Add damapuser to the 'everyone' Group"
  community.general.ldap_attrs:
    dn: "cn=everyone,ou=Groups,{{ dn_suffix }}"
    attributes:
      memberUid: "damapuser"
    bind_dn: "cn=Manager,{{ dn_suffix }}"
    bind_pw: "{{ root_password }}"
    state: "present"

- name: "Add inveniouser to the 'everyone' Group"
  community.general.ldap_attrs:
    dn: "cn=everyone,ou=Groups,{{ dn_suffix }}"
    attributes:
      memberUid: "inveniouser"
    bind_dn: "cn=Manager,{{ dn_suffix }}"
    bind_pw: "{{ root_password }}"
    state: "present"

- name: "Add combineduser to the 'everyone' Group"
  community.general.ldap_attrs:
    dn: "cn=everyone,ou=Groups,{{ dn_suffix }}"
    attributes:
      memberUid: "combineduser"
    bind_dn: "cn=Manager,{{ dn_suffix }}"
    bind_pw: "{{ root_password }}"
    state: "present"

#######################

- name: "User: clusteradmin"
  community.general.ldap_entry:
    dn: "uid=clusteradmin,ou=People,{{ dn_suffix }}"
    objectClass: "inetOrgPerson,posixAccount,shadowAccount"
    attributes:
      uid: "clusteradmin"
      mail: "clusteradmin@example.org" # todo: get domain name
      sn: "Access"
      givenName: "clusteradmin-cluster_admin"
      cn: "clusteradmin-cluster_admin Access"
      title: "Other"
      o: "N/A" #TODO: ORG e.g. Graz University of technology
      departmentNumber: "N/A"
      uidNumber: "40044"
      gidNumber: "10048"
      homeDirectory: "/home/clusteradmin"
    bind_dn: "cn=Manager,{{ dn_suffix }}"
    bind_pw: "{{ root_password }}"
    state: "present"

- name: "Set the clusteradmin password"
  community.general.ldap_passwd:
    dn: "uid=clusteradmin,ou=People,{{ dn_suffix }}"
    passwd: "notprod"
    bind_dn: "cn=Manager,{{ dn_suffix }}"
    bind_pw: "{{ root_password }}"

- name: "Add clusteradmin to the 'cluster_admin' Group"
  community.general.ldap_attrs:
    dn: "cn=cluster_admin,ou=Groups,{{ dn_suffix }}"
    attributes:
      memberUid: "clusteradmin"
    bind_dn: "cn=Manager,{{ dn_suffix }}"
    bind_pw: "{{ root_password }}"
    state: "present"

- name: "Add clusteradmin to the 'everyone' Group"
  community.general.ldap_attrs:
    dn: "cn=everyone,ou=Groups,{{ dn_suffix }}"
    attributes:
      memberUid: "clusteradmin"
    bind_dn: "cn=Manager,{{ dn_suffix }}"
    bind_pw: "{{ root_password }}"
    state: "present"