---
- name: Install packages
  ansible.builtin.include_tasks: "{{ ansible_os_family }}.yml"

- name: Check slapd is running
  ansible.builtin.shell: >-
    set -o pipefail;
    ps -ef |
    awk '/[s]lapd .*-F/{print $2}'
  args:
    executable: /bin/bash
  register: _de_slap__isrunning
  changed_when: false

- name: Kill wrong slapd
  ansible.builtin.command:
    cmd: kill {{ _de_slap__isrunning.stdout }}
  when:
    - _de_slap__isrunning.stdout | length > 0
  args:
    removes: /proc/{{ _de_slap__isrunning.stdout }}/status

- name: "Encode the Root Password"
  ansible.builtin.command:
  args:
    argv:
      - "slappasswd"
      - "-s"
      - "{{ root_password }}"
  register: slappasswd
  failed_when: slappasswd.stdout is not regex('^\{SSHA\}.{32}$')
  changed_when: false
  tags:
    - installation

# TODO: change to new configuration-format
- name: "Generate the OpenLDAP Configuration File"
  ansible.builtin.template:
    src: "slapd.conf.j2"
    dest: "/etc/ldap/slapd.conf"
    owner: root
    mode: "0644"

- name: "Delete the OpenLDAP Configuration Directory"
  ansible.builtin.file:
    path: "/etc/ldap/slapd.d"
    state: absent

- name: "Start the OpenLDAP Server"
  ansible.builtin.systemd:
    name: slapd
    daemon_reload: true
    enabled: true
    state: restarted

- name: Create entities
  ansible.builtin.include_tasks: entities.yml
