galaxy_info:
  author: Sarah Roberts
  description: Installs the OpenLDAP Server for the CyVerse Discovery Environment
  company: CyVerse
  license: BSD

  min_ansible_version: 2.6

  platforms:
  - name: Debian
    versions:
    - 12

  galaxy_tags: []

dependencies: []
